version: '3.8'

services:
  api:
    container_name: tiktok-uploader
    build: .
    ports:
      - "8038:8000"
    volumes:
      - ./cookies:/data/cookies
    environment:
      - COOKIE_DIR=/data/cookies