services:
  api:
    build: .
    ports:
      - "8048:8000"
    volumes:
      - ./cookies:/data/cookies
    environment:
      - COOKIE_DIR=/data/cookies
    restart: unless-stopped
    networks:
      video_generation:
        ipv4_address: 10.20.0.13  # Different IP from previous services

networks:
  video_generation:
    external: true
    name: "Video Generation"
